ALTER TABLE `bot_sw` ADD `creado` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `estado`;
ALTER TABLE `bot_sw` ADD `finalizado` DATETIME NULL DEFAULT NULL AFTER `creado`;
ALTER TABLE `bot_sw_capital_log` ADD `datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;
